create view TOP_ARTIST_S as
select first 10
  GROUP_MEMBER.NAME as artist,
  count(ALBUM.id) as TIMES
from
  ALBUM,
  GROUP_MEMBER,
  FEST,
  ALBUM_GROUP_MEMBER,
  FEST_ALBUMS
where
  GROUP_MEMBER.ID = ALBUM_GROUP_MEMBER. GROUP_MEMBER_ID
  AND  ALBUM_GROUP_MEMBER.ALBUM_ID = ALBUM.ID 
  AND ALBUM.ID = FEST_ALBUMS. ALBUM_ID
  AND FEST_ALBUMS. FEST_ID = FEST.ID
  AND FEST.DATE_OF_OCCURANCE BETWEEN ('01.01.1980 00:00','01.01.2014 00:00')
group by
  GROUP_MEMBER.ID,
order by
  TIMES desc,
  artist;


