CREATE TABLE GROUP (
ID INTEGER,
NAME CHAR(20),
CITY CHAR(20),
DATE_BASEMENT DATE);

CREATE TABLE ARTIST (
ID INTEGER,
GROUP_ID INTEGER,
NAME CHAR(20),
CITY CHAR(20),
ROLE CHAR(50));

ALTER TABLE GROUP ADD CONSTRAINT PK_GROUP PRIMARY KEY (ID);
ALTER TABLE ALBUM ADD "GROUP_ID" INTEGER;
ALTER TABLE ALBUM ADD CONSTRAINT FK_GROUP_ID FOREIGN KEY (GROUP_ID) REFERENCES GROUP(ID);

ALTER TABLE ARTIST ADD CONSTRAINT PK_ARTIST_ID PRIMARY KEY (ID);
ALTER TABLE ALBUM ADD "ARTIST_ID" INTEGER;
ALTER TABLE ALBUM ADD CONSTRAINT FK_ARTIST_ID FOREIGN KEY (ARTIST_ID) REFERENCES ARTIST(ID);

DROP TABLE album_disc;
DROP TABLE group_member;
DROP TABLE album_group_member;

ALTER TABLE DISC ADD "ALBUM_ID" INTEGER;
ALTER TABLE disc  CONSTRAINT FK_ALBUM_ID FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM(ID);

ALTER TABLE SONG ADD "COMPOSER_ID" INTEGER;
ALTER TABLE song CONSTRAINT FK_COMPOSER_ID FOREIGN KEY (COMPOSER_ID) REFERENCES ARTIST(ID);

ALTER TABLE SONG ADD "AUTHOR_ID" INTEGER;
ALTER TABLE song CONSTRAINT FK_AUTHOR_ID FOREIGN KEY (AUTHOR_ID) REFERENCES ARTIST(ID);

ALTER TABLE SONG ADD "CR_DATE" INTEGER;


--CREATE TABLE SESSION (
--ID_SESSION        INTEGER NOT NULL,
--FILM            INTEGER NOT NULL,
--CINEMA             INTEGER NOT NULL,
--COST               INTEGER NOT NULL,
--DATE_AND_TIME    TIME NOT NULL,
--TICKETS_SOLD         INTEGER NOT NULL);

--ALTER TABLE SESSION ADD CONSTRAINT PK_SESSION PRIMARY KEY (ID_SESSION);

--ALTER TABLE SESSION ADD CONSTRAINT FK_SESSION_1 FOREIGN KEY (FILM) REFERENCES "film"("id_film");

--ALTER TABLE SESSION ADD CONSTRAINT FK_SESSION_2 FOREIGN KEY (CINEMA) REFERENCES CINEMA(ID_CINEMA);





